<!-- @migration-task Error while migrating Svelte code: `$:` is not allowed in runes mode, use `$derived` or `$effect` instead
https://svelte.dev/e/legacy_reactive_statement_invalid -->
<script>
	import '../app.css';
	import { browser } from '$app/environment';
	import { onDestroy, onMount } from 'svelte';
	import ToastContainer from '$lib/components/ToastContainer.svelte';
	import OnlineDetector from '$lib/components/OnlineDetector.svelte';
	
	// Use Svelte 5 $props() runes - automatically handles all SvelteKit props
	let { data, children, ...restProps } = $props();
	
	let user = $derived(data.user);
	
	let unregisterSW;

	// Register service worker generated by vite-plugin-pwa
	onMount(async () => {
		if (!browser) return;

		try {
			const { registerSW } = await import('virtual:pwa-register');
			unregisterSW = registerSW({
				onRegisteredSW(swUrl, registration) {
					console.info('Service Worker registered:', { swUrl, registration });
				},
				onRegisterError(error) {
					console.error('Service Worker registration error:', error);
				},
				onNeedRefresh() {
					console.info('Pembaruan PWA tersedia — muat ulang untuk versi terbaru.');
				},
				onOfflineReady() {
					console.info('Aplikasi siap digunakan secara offline.');
				}
			});
		} catch (error) {
			console.error('Gagal menginisialisasi PWA:', error);
		}
	});

	onDestroy(() => {
		unregisterSW?.();
	});
</script>

<svelte:head>
	<title>Absen Guru - Sistem Absensi Guru</title>
	<meta name="description" content="Aplikasi absensi untuk guru" />
	<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
	<link rel="alternate icon" href="/favicon.png" />
	<link rel="apple-touch-icon" href="/favicon.png" />
	<link rel="manifest" href="/manifest.webmanifest" />
</svelte:head>

<!-- Online/Offline Detection with Toast Notifications -->
<OnlineDetector />

<!-- Toast Notifications -->
<ToastContainer />

<div class="min-h-screen bg-base-200">
	{@render children()}
</div>